# Generated by Django 5.0.6 on 2024-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university_id', models.CharField(max_length=100)),
                ('cx', models.FloatField()),
                ('cy', models.FloatField()),
                ('facebook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('official_website', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
