# Generated by Django 5.0.6 on 2024-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
